name: Publish to Homebrew
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - id: revision
        run: echo "revision=$(echo ${GITHUB_REF#refs/tags/} | cut -c2-)" >> $GITHUB_OUTPUT
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: project-env-shell
          formula-path: Casks/project-env-shell.rb
          homebrew-tap: Project-Env/homebrew-tap
          base-branch: main
          download-url: https://github.com/Project-Env/project-env-shell/releases/download/v${{ steps.revision.outputs.revision }}/shell-${{ steps.revision.outputs.revision }}-macos-amd64.tar.gz
          commit-message: bump {{formulaName}} to {{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_RELEASER_TOKEN }}