name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The name of the version which should be released'
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: ubuntu-latest
            asset_file: project-env-shell
            asset_name: project-env-shell-linux-amd64
          - os: windows-latest
            asset_file: project-env-shell.exe
            asset_name: project-env-shell-windows-amd64.exe
            gu_executable_ext: .cmd
          - os: macos-latest
            asset_file: project-env-shell
            asset_name: project-env-shell-macos-amd64
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.os == 'windows-latest'}}
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - run: |
          curl -L https://github.com/Project-Env/project-env-shell/releases/download/0.0.7/project-env-shell-linux-amd64 -o project-env-cli
          chmod +x ./project-env-cli
          ./project-env-cli --config-file=project-env.yml --output-template=github-actions.peb --output-file=github-actions-env.sh
          ./github-actions-env.sh
      - run: mvn -B package -Pnative-image -Drevision=${{ github.event.inputs.version }}
      - id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: v${{ github.event.inputs.version }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: target/${{ matrix.asset_file }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: application/octet-stream

